Week1
opencodegyeonggi/BE-java-ladder pull request #2
Opened 2024-05-16 01:02 UTC by donsonioc2010

맞게 했는지는 잘 모르지만..ㅎ..;; 

- 사다리 게임 구현
  - 랜덤표시의 경우 어떤 조건이다 라는게 없어서, Random을 돌려 0,1,2중에 0이 나오면 사다리가 나오도록 하였습니다.
- 사다리게임 리팩토링
  - 클래스를 쓰지말라는 제약은 없었어서 클래스를 같이 활용했습니다.

2024-05-16 01:37 UTC, birdieHyun reviewed
과제 진행하시느라 고생 많으셨습니다 

저도 아직 배우는 입장이라 틀릴수도 있으니 뭔가 이상한데 싶으면 말씀해주세요 :)

2024-05-16 01:38 UTC, birdieHyun commented on Week1.java
> +public class Week1 {
패키지를 분리하고 클라이언트 코드와 서비스 코드를, 클래스 파일로 분리해보는건 어떨까요?

2024-05-16 01:39 UTC, birdieHyun commented on Week1.java
> +    private static final Scanner scanner = new Scanner(System.in);
Scanner, BufferedReader와 같은 I/O 작업을 하는 객체들을 다 사용하고 난 후 처리해야 할 일은 없을까요?

2024-05-16 01:40 UTC, birdieHyun commented on Week1.java
> +    }
메서드 분리 👍

2024-05-16 01:41 UTC, birdieHyun commented on Week1.java
> +}
mapToObj(i -> ...) 부분에서 i의 정확한 의미를 파악할 수 있도록 변수명을 지어주는건 어떨까요?

2024-05-16 01:43 UTC, birdieHyun commented on Week1.java
> +                System.out.print(p.addStairs(random))
매번 출력이 되는걸로 유추되는데요! 
System.out.println()과 같은 출력 메서드들은 리소스를 많이 사용하기 때문에 다른 방법을 시도해보시는 것도 좋을 것 같아요 :)

2024-05-16 01:46 UTC, birdieHyun commented on Week1.java
> +    private static final String LAST_SADARI = "|\n";
자주 사용되는 String을 상수처리하셨네요 👍 

상수의 네이밍 컨벤션에 대해서 찾아보시면 좋을 것 같아요 :)

2024-05-16 01:48 UTC, birdieHyun requested changes
고생 많으셨습니다 :) 

전체적인 코드 리뷰내용입니다! 

1. 변수명에 의미를 담으면 좋을 것 같아요
2. 클래스 내 변수를 정의하는 순서에 대해서 찾아보시면 좋을 것 같아요

2024-05-20 01:36 UTC, enchooi commented on Week1.java
> +    }
메소드 분리는 이렇게 하는거군요.
메소드 분리의 표본을 본 느낌입니다!

2024-05-20 01:36 UTC, enchooi commented on Week1.java
> +}
앞에서 메소드를 분리한 덕에 사다리 그리는 식은 이렇게 간결해질 수 있나봅니다.
깔끔한 코드 잘 봤습니다!

2024-05-20 05:34 UTC, donsonioc2010 commented on Week1.java
> +    private static final Scanner scanner = new Scanner(System.in);
맞네요..! 오랜만에 IO를 사용하다보니 망각해버렸네요 🥹

2024-05-20 05:35 UTC, donsonioc2010 commented on Week1.java
> +public class Week1 {
처음에 프로젝트 Pull받고서 셋팅이 안되어있어서, 한개의 코드에서 작업해봤는데 , 변경해보도록 하겠습니다 :)

2024-05-20 06:03 UTC, donsonioc2010 commented
1주차 리뷰 수정작업이 늦었네요.. (주말에도 일을 해버려서 ㅎㅎ..)

리뷰다시 해주시면 감사하겠습니다 !

2024-05-20 06:04 UTC, birdieHyun commented on src/main/java/ladder/Week1.java
> +        try (Scanner scanner = new Scanner(System.in)){
👍

2024-05-20 06:09 UTC, birdieHyun commented on src/main/java/ladder/entity/LadderInput.java
> +public class LadderInput {
한 클래스에 책임이 너무 많은것 같아요
입력받는 로직과 다른 로직을 분리해보는건 어떨까요?

2024-05-20 06:10 UTC, birdieHyun commented on src/main/java/ladder/entity/Person.java
> +    }
사용되지 않는 메서드로 보이는데 남겨두신 이유가 있으신가요?

2024-05-20 06:11 UTC, birdieHyun approved these changes
고생하셨습니다 :) 
이번 리뷰는 참고해주시고 다음 과제 진행해주시면 됩니다!

2024-05-20 06:31 UTC, merged